---
title: "Viewing logger files"
author: "Ariana S Huffmyer"
date: "2025"
output: 
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

This script reads and plots environmental data from Hobo loggers. 

# Set Up    

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(stringr)
library(readxl)
library(purrr)
library(lubridate)
library(ggplot2)
library(seacarb)
library(broom)
library(cowplot)
```

# PolyIC loggers 

## Read in files 

Read in Hobo Tidbit files  
```{r}
tidbit.files <- list.files(path="data/environmental/loggers", pattern="*.xlsx", full.names=TRUE)

#will need to change to HST time 
tidbits <- setNames(tidbit.files, tidbit.files) %>%
    map_dfr(read_xlsx, .id = "logger") %>%
    rename(DateTime=`Date-Time (PDT)`, temp.C=`Temp , 째C`)%>%
    select(!`#`)%>%
    select(logger, DateTime, temp.C)%>%
    mutate(logger=sub(".*/", "", logger))%>% #remove the path name
    mutate(logger=sub("_.*", "", logger))%>% #keep only the serial number 
    filter(!temp.C=="NA")

tidbits$DateTime<-as.POSIXct(tidbits$DateTime, format="%m/%d/%Y %H:%M:%S")

```

List the logger serial numbers in this dataframe.  
```{r}
levels(as.factor(tidbits$logger))
```

There are 6 loggers as expected.  

Add in group information. 

```{r}
metadata<-read_xlsx(path="data/environmental/loggers.xlsx")%>%select(c(logger, group))%>%mutate(logger=as.character(logger))

tidbits <- left_join(tidbits, metadata)

levels(as.factor(tidbits$group))
```

Group information is now added.  

## Plot data 

Experiment tanks (Point Whitney)
```{r}
# Dates to filter out
dates_to_filter <- as.Date(c("2024-10-07"))

temp_plot<-tidbits%>%
  filter(group=="experiment")%>%
  mutate(day=as.Date(DateTime))%>%
  filter(!day<dates_to_filter)%>%
  
  ggplot(aes(x=DateTime, y=temp.C))+
  geom_point(alpha=0.7, color="darkgray")+
  geom_smooth(color="black")+
  ylab("Temperature (째C)")+
  xlab("Date")+
  ggtitle("Point Whitney Hatchery")+
  ylim(0,32)+
  theme_classic(); temp_plot

ggsave(temp_plot, filename="figures/environmental/PolyIC_PointWhitney.png", width=6, height=4)
```

FTR tanks (UW)
```{r}
temp_plot2<-tidbits%>%
  filter(group==c("ftr-tanks"))%>%
  
  ggplot(aes(x=DateTime, y=temp.C))+
  facet_wrap(~logger)+
  geom_point(alpha=0.7, color="darkgray")+
  geom_smooth(color="black")+
  ylab("Temperature (째C)")+
  xlab("Date")+
  ggtitle("FTR Tanks")+
  #ylim(0,32)+
  theme_classic(); temp_plot2

temp_plot3<-tidbits%>%
  filter(group==c("ftr-incubations"))%>%
  
  ggplot(aes(x=DateTime, y=temp.C))+
  facet_wrap(~logger)+
  geom_point(alpha=0.7, color="darkgray")+
  geom_smooth(color="black")+
  ylab("Temperature (째C)")+
  xlab("Date")+
  ggtitle("FTR Incubations")+
  #ylim(0,32)+
  theme_classic(); temp_plot3
```
